In [26]:
import pandas as pd

In [27]:
a = pd.read_csv("potential-talents - Aspiring human resources - seeking human resources.csv", header = 0)

In [28]:
b = a["job_title"].str.replace('HR', 'Human Resources', regex=True)

In [30]:
c = []
for i in range(len(b)):
    c.append(b[i])

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [33]:
vect = TfidfVectorizer(min_df=1, stop_words="english") 

In [34]:
c.append("Aspiring human resources")
c.append("seeking human resources")

In [35]:
tfidf = vect.fit_transform(c) 

In [36]:
pairwise_similarity = tfidf * tfidf.T

In [37]:
r = pairwise_similarity[-2:, :].toarray()

In [38]:
r1 = r[0]
r2 = r[1]

In [39]:
r1 = r1[:104]

In [40]:
r2 = r2[:104]

In [44]:
r3 = r1+r2

In [59]:
d = a["connection"].str.replace('500+ ', '500', regex=False)

In [61]:
d = d.astype("int")

In [62]:
d

0       85
1      500
2       44
3      500
4      500
      ... 
99     103
100    500
101     49
102    500
103    500
Name: connection, Length: 104, dtype: int64

In [63]:
e = []
for i in range(len(d)):
    if d[i] == 500:
        e.append(len(d))
    else:
        e.append(d[i]/500*len(d))

In [65]:
import scipy.stats as ss

In [93]:
e1 = ss.rankdata(r3)

In [94]:
len(e1)

104

In [68]:
final_r = e1+e

In [69]:
final_r

array([ 72.68 , 120.5  , 109.152, 120.5  , 120.5  ,  94.208,  89.688,
       174.   ,  89.688, 188.5  ,  16.916, 138.5  , 149.5  ,  72.68 ,
        72.68 , 120.5  , 109.152, 120.5  ,  72.68 , 120.5  , 109.152,
       120.5  , 120.5  ,  94.208,  89.688, 174.   , 191.5  , 171.62 ,
       191.5  , 171.62 ,  72.68 , 120.5  , 109.152, 120.5  , 120.5  ,
        94.208,  89.688, 174.   ,  89.688, 188.5  ,  16.916, 138.5  ,
       149.5  ,  72.68 , 120.5  , 109.152, 120.5  , 120.5  ,  94.208,
        89.688, 174.   ,  89.688, 188.5  ,  16.916, 138.5  , 149.5  ,
        72.68 , 109.152, 120.5  ,  94.208, 174.   , 188.5  ,  16.916,
       138.5  , 149.5  ,  77.856, 152.   , 165.   , 143.   ,  67.056,
       167.   ,  74.04 , 105.456,  85.328, 153.   ,  87.096, 122.072,
       167.   ,  61.456,  27.316, 136.64 ,  95.192,  95.744,  51.4  ,
       120.5  ,  17.332,  24.82 ,  68.744, 123.592,  48.74 ,  24.612,
        51.312,  18.372, 153.32 ,  28.356,  20.452, 114.768,  17.332,
        98.984, 102.

In [70]:
e2 = ss.rankdata(final_r)

In [71]:
e2

array([ 23. ,  63.5,  50.5,  63.5,  63.5,  40. ,  34. ,  96. ,  34. ,
       100.5,   2.5,  77.5,  82.5,  23. ,  23. ,  63.5,  50.5,  63.5,
        23. ,  63.5,  50.5,  63.5,  63.5,  40. ,  34. ,  96. , 103.5,
        92.5, 103.5,  92.5,  23. ,  63.5,  50.5,  63.5,  63.5,  40. ,
        34. ,  96. ,  34. , 100.5,   2.5,  77.5,  82.5,  23. ,  63.5,
        50.5,  63.5,  63.5,  40. ,  34. ,  96. ,  34. , 100.5,   2.5,
        77.5,  82.5,  23. ,  50.5,  63.5,  40. ,  96. , 100.5,   2.5,
        77.5,  82.5,  28. ,  85. ,  88. ,  80. ,  18. ,  90. ,  27. ,
        47. ,  29. ,  86. ,  30. ,  73. ,  90. ,  17. ,  12. ,  75. ,
        43. ,  44. ,  16. ,  63.5,   5.5,  10. ,  19. ,  74. ,  14. ,
         9. ,  15. ,   7. ,  87. ,  13. ,   8. ,  54. ,   5.5,  45. ,
        46. ,  90. ,  11. ,  63.5,  63.5])

In [114]:
import numpy as np
v = np.zeros(len(e2))

In [115]:
v[7] = 208

In [97]:
v1 = pairwise_similarity[7,:].toarray()

In [101]:
v1 = v1[:104]

In [102]:
v1

array([0.07053719, 0.        , 0.1919098 , 0.        , 0.        ,
       0.61327172, 0.10897634, 1.        , 0.10897634, 0.14630621,
       0.        , 0.04798383, 0.09298207, 0.07053719, 0.07053719,
       0.        , 0.1919098 , 0.        , 0.07053719, 0.        ,
       0.1919098 , 0.        , 0.        , 0.61327172, 0.10897634,
       1.        , 0.09904619, 0.13956892, 0.09904619, 0.13956892,
       0.07053719, 0.        , 0.1919098 , 0.        , 0.        ,
       0.61327172, 0.10897634, 1.        , 0.10897634, 0.14630621,
       0.        , 0.04798383, 0.09298207, 0.07053719, 0.        ,
       0.1919098 , 0.        , 0.        , 0.61327172, 0.10897634,
       1.        , 0.10897634, 0.14630621, 0.        , 0.04798383,
       0.09298207, 0.07053719, 0.1919098 , 0.        , 0.61327172,
       1.        , 0.14630621, 0.        , 0.04798383, 0.09298207,
       0.08675925, 0.09905839, 0.41791391, 0.06984249, 0.05374563,
       0.12164105, 0.0934696 , 0.19358172, 0.22652532, 0.05183

In [103]:
v2 = ss.rankdata(v1)

In [108]:
v2

array([ 45. ,  16.5,  87. ,  16.5,  16.5,  97. ,  68. , 102. ,  68. ,
        80.5,  16.5,  34.5,  56.5,  45. ,  45. ,  16.5,  87. ,  16.5,
        45. ,  16.5,  87. ,  16.5,  16.5,  97. ,  68. , 102. ,  60.5,
        77.5,  60.5,  77.5,  45. ,  16.5,  87. ,  16.5,  16.5,  97. ,
        68. , 102. ,  68. ,  80.5,  16.5,  34.5,  56.5,  45. ,  16.5,
        87. ,  16.5,  16.5,  97. ,  68. , 102. ,  68. ,  80.5,  16.5,
        34.5,  56.5,  45. ,  87. ,  16.5,  97. , 102. ,  80.5,  16.5,
        34.5,  56.5,  54. ,  62. ,  94. ,  41. ,  39. ,  73. ,  59. ,
        91. ,  92. ,  38. ,  40. ,  37. ,  73. ,  53. ,  16.5,  93. ,
        49. ,  50. ,  51. ,  16.5,  83. ,  16.5,  75. ,  64. ,  16.5,
        16.5,  16.5,  16.5,  52. ,  16.5,  16.5,  87. ,  16.5,  76. ,
        63. ,  73. ,  16.5,  16.5,  16.5])

In [109]:
final_r1 = v2+e

In [110]:
final_r1

array([ 62.68 , 120.5  ,  96.152, 120.5  , 120.5  ,  97.208,  80.688,
       206.   ,  80.688, 184.5  ,  16.916, 138.5  , 160.5  ,  62.68 ,
        62.68 , 120.5  ,  96.152, 120.5  ,  62.68 , 120.5  ,  96.152,
       120.5  , 120.5  ,  97.208,  80.688, 206.   , 164.5  , 158.62 ,
       164.5  , 158.62 ,  62.68 , 120.5  ,  96.152, 120.5  , 120.5  ,
        97.208,  80.688, 206.   ,  80.688, 184.5  ,  16.916, 138.5  ,
       160.5  ,  62.68 , 120.5  ,  96.152, 120.5  , 120.5  ,  97.208,
        80.688, 206.   ,  80.688, 184.5  ,  16.916, 138.5  , 160.5  ,
        62.68 ,  96.152, 120.5  ,  97.208, 206.   , 184.5  ,  16.916,
       138.5  , 160.5  ,  65.856, 166.   , 198.   , 145.   ,  56.056,
       177.   ,  60.04 ,  92.456,  95.328, 142.   ,  84.096, 122.072,
       177.   ,  54.456,  27.316, 187.64 ,  85.192, 105.744,  61.4  ,
       120.5  ,  83.832,  24.82 ,  78.744, 136.592,  48.74 ,  24.612,
        29.812,  18.372, 138.32 ,  28.356,  20.452, 101.768,  17.332,
        85.984,  84.

In [116]:
for i in range(7):
    v[i] = final_r1[i]
    

In [117]:
for i in range(8,104):
    v[i] = final_r1[i]

In [118]:
v

array([ 62.68 , 120.5  ,  96.152, 120.5  , 120.5  ,  97.208,  80.688,
       208.   ,  80.688, 184.5  ,  16.916, 138.5  , 160.5  ,  62.68 ,
        62.68 , 120.5  ,  96.152, 120.5  ,  62.68 , 120.5  ,  96.152,
       120.5  , 120.5  ,  97.208,  80.688, 206.   , 164.5  , 158.62 ,
       164.5  , 158.62 ,  62.68 , 120.5  ,  96.152, 120.5  , 120.5  ,
        97.208,  80.688, 206.   ,  80.688, 184.5  ,  16.916, 138.5  ,
       160.5  ,  62.68 , 120.5  ,  96.152, 120.5  , 120.5  ,  97.208,
        80.688, 206.   ,  80.688, 184.5  ,  16.916, 138.5  , 160.5  ,
        62.68 ,  96.152, 120.5  ,  97.208, 206.   , 184.5  ,  16.916,
       138.5  , 160.5  ,  65.856, 166.   , 198.   , 145.   ,  56.056,
       177.   ,  60.04 ,  92.456,  95.328, 142.   ,  84.096, 122.072,
       177.   ,  54.456,  27.316, 187.64 ,  85.192, 105.744,  61.4  ,
       120.5  ,  83.832,  24.82 ,  78.744, 136.592,  48.74 ,  24.612,
        29.812,  18.372, 138.32 ,  28.356,  20.452, 101.768,  17.332,
        85.984,  84.

In [119]:
ss.rankdata(v)

array([ 22. ,  63.5,  44.5,  63.5,  63.5,  50. ,  31. , 104. ,  31. ,
        95.5,   2.5,  77.5,  85.5,  22. ,  22. ,  63.5,  44.5,  63.5,
        22. ,  63.5,  44.5,  63.5,  63.5,  50. ,  31. , 101.5,  88.5,
        82.5,  88.5,  82.5,  22. ,  63.5,  44.5,  63.5,  63.5,  50. ,
        31. , 101.5,  31. ,  95.5,   2.5,  77.5,  85.5,  22. ,  63.5,
        44.5,  63.5,  63.5,  50. ,  31. , 101.5,  31. ,  95.5,   2.5,
        77.5,  85.5,  22. ,  44.5,  63.5,  50. , 101.5,  95.5,   2.5,
        77.5,  85.5,  26. ,  90. ,  99. ,  81. ,  16. ,  92. ,  17. ,
        40. ,  41. ,  80. ,  36. ,  73. ,  92. ,  15. ,  11. ,  98. ,
        38. ,  54. ,  18. ,  63.5,  35. ,   9. ,  27. ,  74. ,  14. ,
         8. ,  13. ,   6. ,  75. ,  12. ,   7. ,  53. ,   5. ,  39. ,
        37. ,  92. ,  10. ,  63.5,  63.5])